# Generated by Django 5.0.4 on 2024-07-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
