# Generated by Django 5.0.4 on 2024-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
