# Generated by Django 5.0.4 on 2024-08-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0004_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='images',
        ),
    ]
