# Generated by Django 5.0.4 on 2024-08-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0006_alter_customer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
