# Generated by Django 5.1.3 on 2024-12-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0008_alter_customer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='images',
            field=models.ImageField(default='', upload_to='upload/'),
        ),
    ]
